name: cmder-release-workflow

on:
  push:
    tags: 
      - 'v*'

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: "Setup Rust environment"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: cargo test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Publish package
        uses: katyo/publish-crates@v1
        with:
          registry-token: ${{secrets.CRATES_IO_TOKEN}}

      
